name: CI

on:
  push:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # 指定 Java 发行版
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build app
        run: ./gradlew assembleRelease

      - name: Upload built APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Release_${{ env.VERSION }}.apk
          path: app/build/outputs/apk/release/${{ env.APK_FILE }}
